version: '3.2'
services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.99.100:3000
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - TZ="America/Bahia"
    ports:
      - 3000:3000
    user: "1001"
    networks:
      - gateway
    volumes:
      - "./grafana/:/var/lib/grafana"
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - gateway
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  web-project:
    build:
      context: web
      dockerfile: Dockerfile
    image: monitoring
    ports:
      - 8090:8090
    networks:
      - gateway
networks:
  gateway: {}